const createProviderFoundation = require("./ProviderAdapterFactory");

module.exports = {
  ProviderAdapterConfig: require("./ProviderAdapterConfig"),
  ProviderAdapterInterface: require("./ProviderAdapterInterface"),
  ProviderOperation: require("./ProviderOperation"),
  BaseProviderAdapter: require("./BaseProviderAdapter"),
  ProviderRequest: require("./models/ProviderRequest"),
  ProviderResponse: require("./models/ProviderResponse"),
  ProviderError: require("./models/ProviderError"),
  ProviderAdapterRegistry: require("./ProviderAdapterRegistry"),
  ProviderAdapterResolver: require("./ProviderAdapterResolver"),
  ProviderCapabilityValidator: require("./ProviderCapabilityValidator"),
  ProviderAdapterFeatureGate: require("./ProviderAdapterFeatureGate"),
  ProviderAdapterHealthContract: require("./ProviderAdapterHealthContract").ProviderAdapterHealthContract,
  ProviderHealthStatus: require("./ProviderAdapterHealthContract").ProviderHealthStatus,
  MTNMoMoAdapter: require("./adapters/MTNMoMoAdapter"),
  AirtelMoneyAdapter: require("./adapters/AirtelMoneyAdapter"),
  FlutterwaveAdapter: require("./adapters/FlutterwaveAdapter"),
  StripeAdapter: require("./adapters/StripeAdapter"),
  PaypackAdapter: require("./adapters/PaypackAdapter"),
  WebhookVerificationInterface: require("./WebhookVerificationInterface"),
  WebhookVerificationContract: require("./WebhookVerificationContract"),
  ProviderIdempotencyContract: require("./ProviderIdempotencyContract"),
  ProviderIdempotencyKey: require("./ProviderIdempotencyKey"),
  ProviderReference: require("./ProviderReference"),
  ProviderReferenceContract: require("./ProviderReferenceContract"),
  ProviderReferenceInterface: require("./ProviderReferenceInterface"),
  ProviderCapabilityError: require("./errors/ProviderCapabilityError"),
  ProviderAdapterDisabledError: require("./errors/ProviderAdapterDisabledError"),
  ProviderAdapterNotRegisteredError: require("./errors/ProviderAdapterNotRegisteredError"),
  ProviderCurrencyNotSupportedError: require("./errors/ProviderCurrencyNotSupportedError"),
  ProviderCountryNotSupportedError: require("./errors/ProviderCountryNotSupportedError"),
  createProviderFoundation,
  ProviderAdapterFactory: createProviderFoundation,
};
